global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'orbis_placeholders'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'  # astro service
          - 'host.docker.internal:8081'  # price service
          - 'host.docker.internal:8082'  # correlator or alert service
